/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: '#0b1326',
        'surface-dim': '#0b1326',
        'surface-bright': '#31394d',
        'surface-container-lowest': '#060e20',
        'surface-container-low': '#131b2e',
        'surface-container': '#171f33',
        'surface-container-high': '#222a3d',
        'surface-container-highest': '#2d3449',
        'on-surface': '#dae2fd',
        'on-surface-variant': '#bacac5',
        'inverse-surface': '#dae2fd',
        'inverse-on-surface': '#283044',
        outline: '#859490',
        'outline-variant': '#3c4a46',
        'surface-tint': '#3cddc7',
        primary: '#57f1db',
        'on-primary': '#003731',
        'primary-container': '#2dd4bf',
        'on-primary-container': '#00574d',
        'inverse-primary': '#006b5f',
        secondary: '#b7c8e1',
        'on-secondary': '#213145',
        'secondary-container': '#3a4a5f',
        'on-secondary-container': '#a9bad3',
        tertiary: '#afe0ff',
        'on-tertiary': '#00354a',
        'tertiary-container': '#5ec9ff',
        'on-tertiary-container': '#005371',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'primary-fixed': '#62fae3',
        'primary-fixed-dim': '#3cddc7',
        'on-primary-fixed': '#00201c',
        'on-primary-fixed-variant': '#005047',
        'secondary-fixed': '#d3e4fe',
        'secondary-fixed-dim': '#b7c8e1',
        'on-secondary-fixed': '#0b1c30',
        'on-secondary-fixed-variant': '#38485d',
        'tertiary-fixed': '#c4e7ff',
        'tertiary-fixed-dim': '#7bd0ff',
        'on-tertiary-fixed': '#001e2c',
        'on-tertiary-fixed-variant': '#004c69',
        background: '#0b1326',
        'on-background': '#dae2fd',
        'surface-variant': '#2d3449',
      },
      fontFamily: {
        inter: ['Inter', 'sans-serif'],
        jetbrains: ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'data-mono': ['14px', { lineHeight: '18px', letterSpacing: '0.02em', fontWeight: '500' }],
        'label-caps': ['10px', { lineHeight: '12px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
      borderRadius: {
        'sm': '0.125rem',
        DEFAULT: '0.25rem',
        'md': '0.375rem',
        'lg': '0.5rem',
        'xl': '0.75rem',
        'full': '9999px',
      },
      spacing: {
        'unit': '4px',
        'gutter': '16px',
        'margin-mobile': '16px',
        'margin-desktop': '24px',
        'container-max': '1600px',
      }
    },
  },
  plugins: [],
}
